criterion:
  classes_per_batch: 15
  me_max: true
  sharpen: 0.25
  supervised_imgs_per_class: 7
  supervised_views: 1
  temperature: 0.1
  unsupervised_batch_size: 64
data:
  color_jitter_strength: 1.0
  data_seed: null
  dataset: imagenet
  image_folder: 
  label_smoothing: 0.1
  multicrop: 6
  normalize: true
  root_path: /scratch2/clear/dataset/
  image_folder: ImageNet2012/
  subset_path: imagenet_subsets/
  unique_classes_per_rank: true
  unlabeled_frac: 0.9
logging:
  folder: /scratch2/clear/larbez/Workspace/PAWS/imagenet_test/
  write_tag: paws
meta:
  copy_data: False
  device: cuda:0
  load_checkpoint: false
  model_name: resnet50
  output_dim: 2048
  read_checkpoint: null
  use_fp16: true
  use_pred_head: true
optimization:
  epochs: 100
  final_lr: 0.064
  lr: 6.4
  momentum: 0.9
  nesterov: false
  start_lr: 0.3
  warmup: 10
  weight_decay: 1.0e-06
