data:
  data_seed: 152
  dataset: imagenet_fine_tune
  image_folder: imagenet_full_size/061417/
  normalize: true
  num_classes: 1000
  root_path: datasets/
  subset_path: imagenet_subsets/
  unlabeled_frac: 0.90
logging:
  folder: /path_to_save_models_and_logs/
  pretrain_path: paws-latest.pth.tar
  write_tag: paws-latest
meta:
  copy_data: true
  device: cuda:0
  load_checkpoint: false
  master_port: 4029
  model_name: resnet50
  training: true
  use_fp16: true
optimization:
  epochs: 50
  lr: 0.02
  use_lars: false
  weight_decay: 0.0
  zero_init: true
